HOST: http://54.68.89.158/apis/dec/

# API DEC

## Cliente [/clientes/{_id}]

- `_id`          Automatically assigned

+ Parameters
    + _id (required, int) ... Número interno del Cliente
    
+ Model (application/hal+json)

    + Body

            {
                "_id": 6,
            }

## Retrieve a single Cliente [GET]

    + Response 200 (application/json)

        [Cliente][]
    
    + Response 404 (application/json)

        { 
            "error": "Resource not found" 
        }